FROM node:lts-alpine AS dev-builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


FROM dev-builder AS development
EXPOSE 5173
# CMD ["npm", "run", "dev", "--host", "0.0.0.0"]
CMD ["npm", "run", "dev"]
