# for Development Docker-Compose

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - static_volume:/app/src/static
      # - media_volume:/app/media
    env_file:
      - ./backend/.env
      - ./database/.env
    environment:
      - ENV=${ENV}
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - backend
      - shared

  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
      dockerfile: Dockerfile-Dev  # In Development
    ports:
      - 127.0.0.1:5173:5173    # In Development
    env_file:
      - ./frontend/.env
    environment:
      - ENV=${ENV}   
    volumes:
      - ./frontend:/app:rw   # In Development
      - frontend_dist:/app/dist
    # expose:
    #   - 5173
    networks:
      - shared

  db:
    image: postgres:15
    restart: unless-stopped
    # ports:  
    #   - "127.0.0.1:5432:5432" # In Development
    env_file:
      - ./database/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "127.0.0.1:80:80"
      # - "443:443" # HTTPS 사용 시
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static:ro # Django static serve
      # - media_volume:/var/www/media:ro # Django media serve
      - frontend_dist:/var/www/frontend:ro # Vue build file serve
      # - certbot-etc:/etc/letsencrypt # HTTPS (Let's Encrypt)
      # - certbot-var:/var/lib/letsencrypt # HTTPS (Let's Encrypt)
      # - fe-dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - shared

volumes:
  pgdata:
  static_volume:
  # media_volume:
  frontend_dist:

networks:
  shared: 
  backend:

